### ISSUE TITLE
Extend existing array option overwriting values in array

### ISSUE THREAD

**Issue by EricLarson2020** [magynhard/yaml_extend#16]
Please see the failing spec here: #15

**Comment by magynhard** [comment]
As you found out (https://github.com/magynhard/yaml_extend/pull/15) it is a issue or missing feature of the underlying `deep_merge` gem, i close this related issue as well.

Maybe one of the options of `deep_merge` fits your desire or a feature request or even a pull request with a solution there might be necessary.

https://github.com/danielsdeleo/deep_merge

Thank you!
