### ISSUE TITLE
Need to pass options through to Psych

### ISSUE THREAD

**Issue by weedySeaDragon** [magynhard/yaml_extend#19]
I've been using yaml_extend and like it. Thanks!

I now need to pass the `symbolize_names` option to Psych. Specifically I need to pass `symbolize_names: true`.
I don't see a way to do this. Is there a way to pass options thru to Psych?  Am I overlooking something?

**Comment by weedySeaDragon** [comment]
Nevermind. I've figured out a workaround.

**Comment by magynhard** [comment]
Thank you for your report. I think others could need this feature as well. I will reopen this issue to add the `symbolize_names` as additional pass through option.
